version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: poluostrov_mongo
      DATABASE_HOST: localhost
      DATABASE_PORT: 27017
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: poluostrov_mongo
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - ./data:/data/db
